baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Shamil's place"
theme = "anubis2"

[author]
name = "Shamil Carela"

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style
